#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

branches:
  # whitelist
  only:
    - master

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf true

# fetch repository as zip archive. default is "false"
#shallow_clone: true

# set clone depth
clone_depth: 3

# environment variables
environment:
  MINGW_DIR: C:\CPP\compiler\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin

cache:
  - C:\CPP\extlibs

# scripts that run after cloning repository
install:
  # begin prepare for simulate local dev environment
  - mkdir C:\CPP
  - mkdir C:\CPP\compiler
  - mkdir C:\CPP\tools
  - mkdir C:\CPP\extlibs
  - move C:\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0 C:\CPP\compiler
  - move C:\msys64 C:\CPP\tools
  #- set PATH=%MINGW_DIR%;%PATH%
  - set PATH=%MINGW_DIR%;C:\Program Files\7-Zip
  # Installing msys/boost
  #- C:\CPP\tools\msys64\usr\bin\bash -l -c "pacman -Sy --noconfirm mingw64/mingw-w64-x86_64-boost 2>&1"
  #- C:\CPP\tools\msys64\usr\bin\bash -l -c "pacman -Sy --noconfirm mingw-w64-x86_64-wxWidgets 2>&1"
  #- C:\CPP\tools\msys64\usr\bin\bash -l -c "pacman -Sy --noconfirm mingw-w64-i686-wxWidgets 2>&1"
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.0.4/wxWidgets-3.0.4.7z'
  - 7z x wxWidgets-3.0.4.7z -oC:\CPP\extlibs\wxwidgets-3.0.4
  - set PATH=C:\CPP\tools\msys64\usr\bin;%PATH%
  - cd C:\CPP\extlibs\wxwidgets-3.0.4\build\msw
  - dir
  - set
  - mingw32-make --version
  - type -p mingw32-make
  - mingw32-make -j1 -f makefile.gcc BUILD=debug   SHARED=0 UNICODE=1 CXXFLAGS="-g -static -mthreads -pipe -std=gnu++17 -m32 -Wall -O0 -DwxDEBUG_LEVEL=1" setup_h
  - mingw32-make -j9 -f makefile.gcc BUILD=debug   SHARED=0 UNICODE=1 CXXFLAGS="-g -static -mthreads -pipe -std=gnu++17 -m32 -Wall -O0 -DwxDEBUG_LEVEL=1"
  #
  # start build project
#  - mkdir build
#  - cd build
#  - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
#  - cmake --build .
#  - cd test
#  - ctest


#---------------------------------#
#       build configuration       #
#---------------------------------#

# to disable automatic builds
build: off