#https://github.com/ainfosec/ci_helloworld

#
# Configuration
#
language: cpp
dist: xenial

#
# Build Dependencies
#
before_script:
- mkdir build
- cd build

#
# Build Matrix
#
matrix:
  include:

  #
  # Build Release
  #
  - os: linux
    env:
      - TEST="Build Release"

    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          #- libboost-all-dev
          - libwxgtk3.0-dev:i386
          #- libwxgtk3.0-dev
          - doxygen
          - graphviz
          - pandoc
          - libc6-dev-i386
          #- libc6-dev
          - gcc-multilib
          - g++-multilib

    compiler: gcc

    before_install:
      - sudo add-apt-repository ppa:alexlarsson/flatpak -y
      - sudo apt update
      - sudo apt install flatpak
      - sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      - sudo flatpak install --assumeyes flathub org.freedesktop.Platform//18.08
      - wget https://github.com/wxFormBuilder/wxFormBuilder/releases/download/v3.9.0/wxformbuilder.flatpak
      - sudo flatpak install --assumeyes wxformbuilder.flatpak
      - ls /var/lib/flatpak/app/org.wxformbuilder.wxFormBuilder
      - sudo flatpak run org.wxformbuilder.wxFormBuilder
      - wxformbuilder -g wxfb/wxfb_info_dialog.fbp
      - wxformbuilder -g wxfb/wxfb_main_frame.fbp
      # Install latest boost
      - wget -O boost.tar.bz2 https://sourceforge.net/projects/boost/files/boost/1.70.0/boost_1_70_0.tar.bz2/download
      - tar xjf boost.tar.bz2
      - ls
      - cd boost_1_70_0
      - sudo ./bootstrap.sh --prefix=/usr/local
      - sudo ./b2 headers
      - sudo ./b2 install --with-filesystem --with-date_time --with-test
      - cd ..
    
    script:
      - cmake -DCMAKE_BUILD_TYPE=Release ..
      - make
