#https://github.com/ainfosec/ci_helloworld

#
# Configuration
#
language: cpp
dist: xenial

#
# Build Dependencies
#
before_script:
- mkdir build
- cd build

#
# Build Matrix
#
matrix:
  include:

  #
  # Build Release
  #
  - os: linux
    env:
      - TEST="Build Release"

    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - libboost-all-dev
          - libwxgtk3.0-dev

    compiler: gcc

    before_install:
      # Install a supported cmake version (>= 3.4.3)
      #- wget -O cmake.sh https://github.com/Kitware/CMake/releases/download/v3.15.3/cmake-3.15.3-Linux-x86_64.sh
      #- sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
      - cmake --version
    
    script:
      - mkdir build
      - cd build
      - cmake ../
      - make
