#ifndef __C_wxMainFrame__
#define __C_wxMainFrame__

/**
@file
Subclass of C_wxfbMainFrame, which is generated by wxFormBuilder.
*/

#include <winsock2.h>
#include "C_wxfbMainFrame.h"

//// end generated include

#include <wx/valnum.h>
#include <wx/fileconf.h>      // for wxFileConfig
#include "helpers/helpers.h"
#include "prjprops/prjprops.h"
#include "C_wxDlgInfo.h"

const std::string sNEWLINE   = "\n";
const std::string sBLANK     = " ";

namespace bp = boost::process; //we will assume this for all further examples

/** Implementing C_wxfbMainFrame */
class C_wxMainFrame : public C_wxfbMainFrame
{
	public:
		/** Constructor */
		C_wxMainFrame( wxWindow* parent );
	//// end generated class members
		~C_wxMainFrame();

	private:
        double m_length;
        double m_height;
        double m_scale;
        std::string m_inkscape_file_content;
        std::string m_project_file;
        std::string m_project_file_content;

        //Initialisation of GUI
        void init_validators(void);
        void init_textctrl_length_width(void);
        void init_filepickers(void);

        //Reading/writing/checking settings.ini
        void read_settings(void);
        wxString check_file_present(wxString path_file);
        void write_settings(void);

        void get_inkscape_file_content(void);
        void shipout_inkscape_file(void);
        void update_form_values(void);
        void content_parse(void);
        void content_serialize(void);

        void set_format(std::string height, std::string width);
        std::string get_orientation(void);
        void set_orientation(std::string orientation);
        std::string get_dpi(void);
        void set_dpi(std::string dpi);


        //GUI Actions
        void OnBtnClickStartMapDefBounds( wxCommandEvent& event );
		void OnText_geometry_bounds( wxCommandEvent& event );
		void OnCombobox_format( wxCommandEvent& event );
        void OnButtonClick_fct1( wxCommandEvent& event );
		void OnButtonClick_create_territory_card( wxCommandEvent& event );
		void OnFileMenuNew( wxCommandEvent& event );
		void OnFileMenuOpen( wxCommandEvent& event );
		void OnFileMenuSave( wxCommandEvent& event );
		void OnFileMenuSaveAs( wxCommandEvent& event );
		void OnFileMenuQuit( wxCommandEvent& event );
		void OnHelpMenuAbout( wxCommandEvent& event );
};

#endif // __C_wxMainFrame__
